name: LifeStealFreeV2
version: '1.0.0'
main: plugins.lifestealfreev2.Main
api-version: '1.20'
permissions:
  LifeSteal.Revive:
    default: true
  LifeSteal.Heart:
    default: true
  LifeSteal.Item:
    default: false
  LifeSteal.Sethealth:
    default: false
  LifeSteal.Revive.Player:
    default: false
  LifeSteal.*:
    children:
      LifeSteal.Sethealth: true
      LifeSteal.Revive: true
      LifeSteal.Heart: true
      LifeSteal.Item: true
      LifeSteal.Revive.Player: true